### DISCUSSION TITLE
Not able to import webfonts

### DISCUSSION THREAD

**Discussion by jrson83** [nanojsx/nano#57] [Help / Questions] [answered]
With v23 I can't import webfonts. I tried adding to the top of the `styles.scss`:
```css
@import url("https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:100,300,400");

body {
  font-family: 'Montserrat', 'Roboto', sans-serif;
}
```
If I inspect the `body` I see a striked through font-family:
```css
body {
    font-family: &quot;
}
```
If I try the fonts without single quotes, it just uses sans-serif.

Tried using file-loader with webpack:
```webpack
{
  test   : /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
  use : 'file-loader'
},
```

I also tried [typefaces](https://github.com/KyleAMathews/typefaces/tree/master/packages), but had the same issue like described in this post: [Importing packages from the Typefaces project breaks Webpack](https://github.com/reactql/kit/issues/72)

Again I tried the package [webfontloader](https://www.npmjs.com/package/webfontloader) with [@types/webfontloader](https://www.npmjs.com/package/@types/webfontloader) but the font is just not changing.
